### PR TITLE
log_files: remove synchronous DownloadLogFile

### PR DESCRIPTION
**Pull request by dayjaby**
fixes https://github.com/mavlink/MAVSDK-Python/issues/534

### CODE REVIEW

**Review by JonasVautherin — APPROVED** [review]

**Review by julianoes — APPROVED** [review]
Thanks!

**Comment by julianoes** [comment]
I don't think that's the right fix. We will have the same problem in other places, right? Or why would this one be special?

**Comment by JonasVautherin** [comment]
This is the only place where we have both `SubscribeDownloadFile` and `DownloadFile`. That should be forbidden, because both end up generating a function called `download_file()` in Python and `downloadFile` in Java. The `Subscribe-` prefix just indicates that it is a stream.

Arguably a better fix would be to detect that it is a stream with the `stream` keyword in the response, and keep `Subscribe` in the name. But well... that's how it is now :sweat_smile:

**Comment by julianoes** [comment]
Oh, I see. That should be forbidden indeed.

**Comment by julianoes** [comment]
@JonasVautherin so I guess we can leave this as is and go through with the changes in C++, towards v2.0? Right?

**Comment by JonasVautherin** [comment]
Yes!

**Pull request merged**
