### PR TITLE
add SetRateSysStatus

### PR DESCRIPTION
**Pull request by 41Mo**
# Related PRs

- MAVSDK: https://github.com/mavlink/MAVSDK/pull/1998

# Description:

This pr adds a new SetRateSysStatus request that will improve API usage as described in mavlink/MAVSDK#1996.

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
I would call it SetRateHealth, otherwise it's not clear what it changes.
What do you think?

**Comment by 41Mo** [comment]
SYS_STATUS message is a little confusing, because it contains not only health data, but also basic battery information.
So i am not sure, how to properly call it. So what do you think?

**Comment by 41Mo** [comment]
SYS_STATUS message is a little confusing, because it contains not only health data, but also basic battery information.
I am not sure how to name it properly. What do you think, just HEALTH is enough?

**Comment by 41Mo** [comment]
In my opinion better call it SYS_STATUS and give a reference to mavlink message defenition and small commentary about content of this message

**Comment by julianoes** [comment]
Right, I can see how it's confusing. The other question is if PX4 actually allows you to send the sys status quicker.

Or what about just not allowing this message to be sent at a higher rate? Is it really required at a higher rate?

**Comment by 41Mo** [comment]
@julianoes  yes, good point. In my practice, there was no case when it was required to receive the status with greater frequency.

Maybe then just add the frequency setting without additional api, directly to the plugin's init?

**Comment by julianoes** [comment]
Ok, and you would request it at 1Hz?

**Comment by 41Mo** [comment]
Yes

**Comment by julianoes** [comment]
Ok makes sense. That's for the cases where it's not already automatically sent at 1Hz.

**Comment by julianoes** [comment]
I'm sorry I didn't act on this earlier. Sometimes life takes over.

Anyway, it looks like the battery rate has been fixed by https://github.com/mavlink/MAVSDK/pull/2021 and I doubt we need health information faster than 1 Hz. I believe PX4 won't send it out quicker anyway as the pre-flight checks don't run faster than 1 Hz anyway.

 If I'm wrong with that let me know.

**Pull request closed without merging**
