### PR TITLE
Added new mission items

### PR DESCRIPTION
**Pull request by rligocki**

### CODE REVIEW

**Review by JonasVautherin — APPROVED** [review]
LGTM, I'll merge that once the C++ PR is ready

**Comment by rligocki** [comment]
C++ PR should be ready. Now problem is, how to solve conflicts with proto. I can update proto in C++ to this commit, but then before PR is finished it must be changed back to proto main. Am I wrong?

**Comment by JonasVautherin** [comment]
You're right. Update your PR to this commit so that we can see that it works and the CI passes the test. Then I can merge this one, you can update the C++ one to point to mavsdk-proto `main`, and I can merge the C++ PR.

We do it this way because if we merge the proto before the C++ PR is ready, sometimes it gets inactive and we have to revert the proto side (which actually happened for this very PR :innocent:)

**Review by julianoes — APPROVED** [review]

**Comment by julianoes** [comment]
@rligocki I rebased your branch on top of upstream/main and force-pushed it. I did an interactive rebase to squash your commits into one.

**Review by JonasVautherin — APPROVED** [review]

**Review by julianoes — DISMISSED** [review]

**Review by julianoes — DISMISSED** [review]

**Comment by julianoes** [comment]
Rebased and force pushed.

**Review by JonasVautherin — APPROVED** [review]

**Pull request merged**
