### PR TITLE
Add param_server

### PR DESCRIPTION
**Pull request by bazfp**
API for setting/getting the parameters in MAVSDK as a parameter server.

Implementation Here: https://github.com/mavlink/MAVSDK/pull/1473

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
Thanks for the pull request. So I'm a wondering about the wording because we are not really "getting" or "setting" a param but rather "providing" a param and then getting an update on it, right? I guess I don't have a better suggestion, I was just hoping it would be somehow distinguishable from the non-server version.

**Comment by bazfp** [comment]
Yes I have thought about the same thing. I think setting and getting makes sense as we're setting/getting things on the `param_server` side instead of on the vehicle side - but the API can be confusing as it's the same as the `param` plugin.

Alternative options are `provide` `retrieve`. I could perhaps even expand the API to act more CRUD-like `create` `read` `update` `delete` - Although `creating` and `deleting` is likely to be of limited use?

Open to suggestions.

**Comment by julianoes** [comment]
@JonasVautherin any opinion?
I like `provide`, `retrieve`.

**Review by julianoes — APPROVED** [review]

**Comment by julianoes** [comment]
@JonasVautherin any objections before I merge this?

**Review by JonasVautherin — APPROVED** [review]
Looking very clean :+1:

**Pull request merged**
