### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Output: https://github.com/cclauss/MAVSDK-Proto/actions

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Thanks for the suggestion! I get the idea, but I'm a bit reluctant to add a linter without committing to making it pass.

For instance, it complains about typo like "NED -> NEED", but NED means "North-East-Down". So one would have to solve that somehow. Same for all the other checks.

Happy to reconsider it if somebody puts resources on making the tests pass, though :+1:

**Comment by TSC21** [comment]
> Thanks for the suggestion! I get the idea, but I'm a bit reluctant to add a linter without committing to making it pass.
> 
> For instance, it complains about typo like "NED -> NEED", but NED means "North-East-Down". So one would have to solve that somehow. Same for all the other checks.
> 
> Happy to reconsider it if somebody puts resources on making the tests pass, though 👍

You would need to add a custom dictionary to make it pass.

**Comment by cclauss** [comment]
`codespell --ignore-words-list="ned,positionned"`

**Review by JonasVautherin — APPROVED** [review]
Very nice, thanks! Other tests can be added later :blush:

**Comment by julianoes** [comment]
We have spelling mistakes, no way! :smile:

**Pull request merged**
